module.exports = [
    "strapi::errors",
    {
        name: "strapi::security",
        config: {
            contentSecurityPolicy: {
                useDefaults: true,
                directives: {
                    "frame-src": [
                      "'self'",
                      "youtube.com",
                      "www.youtube.com",
                      "vimeo.com",
                      "*.vimeo.com",
                      "facebook.com",
                      "www.facebook.com",
                    ],
                    "script-src": [
                        "'self'",
                        "*.tinymce.com",
                        "*.tiny.cloud",
                        "https:",
                        "editor.unlayer.com",
                    ],
                    "connect-src": [
                        "'self'",
                        "*.tinymce.com",
                        "*.tiny.cloud",
                        "blob:",
                        "*.strapi.io",
                        "ws:",
                        "wss:",
                        "https:"
                    ],
                    "img-src": [
                        "'self'",
                        "*.tinymce.com",
                        "*.tiny.cloud",
                        "data:",
                        "blob:",
                        "cdn.jsdelivr.net",
                        "strapi.io",
                        "dl.airtable.com",
                        "s3.amazonaws.com",
                    ],
                    "style-src": [
                        "'self'",
                        "'unsafe-inline'",
                        "*.tinymce.com",
                        "*.tiny.cloud",
                    ],
                    "font-src": [
                        "'self'",
                        "*.tinymce.com",
                        "*.tiny.cloud",
                        "editor.unlayer.com",
                    ],
                    upgradeInsecureRequests: null,
                },
            },
        },
    },
    "strapi::cors",
    "strapi::poweredBy",
    "strapi::logger",
    "strapi::query",
    "strapi::body",
    "strapi::session",
    "strapi::favicon",
    "strapi::public",
];
